---
title: "R Notebook"
output: html_notebook
---

Adicional a la normalidad, también se realizaron otros supuestos acerca de los residuales ($r_i$):

$$E(r) = 0$$
$$V(r) = \sigma^2$$
$$Cov(r_i, r_j) = 0 \qquad \forall  \qquad  i \neq j$$
## Esperanza de residuales igual a 0 


## Varianza de residuales es igual a $\sigma^2$ (Homocedasticidad)
¿Qué pasa si la varianza del error no es constante?

Un supuesto importante de la regresión lineal es que los residuales r_i son homoscedásticos: todos tienen la misma varianza. Se examinará como determinar si se cumple el supuesto, qué sucede si no se cumple y como se soluciona.

### Métodos gráficos




### ¿Cómo se soluciona?
Uno de los métodos para solucionar la heteroscedasticidad es utilizar Minimos Cuadrados Generalizados en lugar de Minimos Cuadrados Ordinarios. Este tema está fuera del scope del curso, pero pueden consultarlo en la sección 11.3 de Guajarati.


## Covarianza de residuales es 0


```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

